### ISSUE TITLE
sequential editing size

### ISSUE THREAD

**Issue by VRCMF** [XZhang00/LU-LAFNs#1]
Hi,

Thank you for your work. Can i ask the size of sequential editing? Is the size of sequential editing is 1?
![捕获](https://github.com/user-attachments/assets/d98bf98d-78ee-43fe-b31c-bbbc8991c864)

**Comment by XZhang00** [comment]
Yes, the size of sequential editing is 1. "An instance of editing fact" includes the multilingual versions of an edit descriptor.

**Comment by VRCMF** [comment]
> Yes, the size of sequential editing is 1. "An instance of editing fact" includes the multilingual versions of an edit descriptor.

Thank you for clarifying. Will close the issue
